// Code generated by protoc-gen-go. DO NOT EDIT.
// source: deploy_controller.proto

/*
Package protos is a generated protocol buffer package.

It is generated from these files:
	deploy_controller.proto

It has these top-level messages:
	SSH
	Node
	TestConnectionRequest
	TestConnectionReply
	CheckNodesRequest
	CheckNodesReply
	CheckItem
	ItemCheckResult
	NodeCheckResult
	GetCheckNodesResultRequest
	GetCheckNodesResultReply
	ClusterConfig
	Taint
	NodeDeployConfig
	DeployRequest
	DeployReply
	GetDeployResultRequest
	DeployComponent
	DeployItem
	DeployItemResult
	GetDeployResultReply
*/
package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NodeRoleType int32

const (
	NodeRoleType_ETCD   NodeRoleType = 0
	NodeRoleType_MASTER NodeRoleType = 1
	NodeRoleType_WORKER NodeRoleType = 2
)

var NodeRoleType_name = map[int32]string{
	0: "ETCD",
	1: "MASTER",
	2: "WORKER",
}
var NodeRoleType_value = map[string]int32{
	"ETCD":   0,
	"MASTER": 1,
	"WORKER": 2,
}

func (x NodeRoleType) String() string {
	return proto.EnumName(NodeRoleType_name, int32(x))
}
func (NodeRoleType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type SSH_AuthType int32

const (
	SSH_PASSWORD   SSH_AuthType = 0
	SSH_PRIVATEKEY SSH_AuthType = 1
)

var SSH_AuthType_name = map[int32]string{
	0: "PASSWORD",
	1: "PRIVATEKEY",
}
var SSH_AuthType_value = map[string]int32{
	"PASSWORD":   0,
	"PRIVATEKEY": 1,
}

func (x SSH_AuthType) String() string {
	return proto.EnumName(SSH_AuthType_name, int32(x))
}
func (SSH_AuthType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

// SSH contains the ssh login info.
type SSH struct {
	Port uint32    `protobuf:"varint,1,opt,name=port" json:"port,omitempty"`
	Auth *SSH_Auth `protobuf:"bytes,2,opt,name=auth" json:"auth,omitempty"`
}

func (m *SSH) Reset()                    { *m = SSH{} }
func (m *SSH) String() string            { return proto.CompactTextString(m) }
func (*SSH) ProtoMessage()               {}
func (*SSH) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SSH) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *SSH) GetAuth() *SSH_Auth {
	if m != nil {
		return m.Auth
	}
	return nil
}

type SSH_Auth struct {
	Type       SSH_AuthType `protobuf:"varint,1,opt,name=type,enum=protos.SSH_AuthType" json:"type,omitempty"`
	Credential string       `protobuf:"bytes,2,opt,name=credential" json:"credential,omitempty"`
}

func (m *SSH_Auth) Reset()                    { *m = SSH_Auth{} }
func (m *SSH_Auth) String() string            { return proto.CompactTextString(m) }
func (*SSH_Auth) ProtoMessage()               {}
func (*SSH_Auth) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *SSH_Auth) GetType() SSH_AuthType {
	if m != nil {
		return m.Type
	}
	return SSH_PASSWORD
}

func (m *SSH_Auth) GetCredential() string {
	if m != nil {
		return m.Credential
	}
	return ""
}

// Node contains the node metadata info
type Node struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Ip   string `protobuf:"bytes,2,opt,name=ip" json:"ip,omitempty"`
	Ssh  *SSH   `protobuf:"bytes,3,opt,name=ssh" json:"ssh,omitempty"`
}

func (m *Node) Reset()                    { *m = Node{} }
func (m *Node) String() string            { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()               {}
func (*Node) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Node) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Node) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Node) GetSsh() *SSH {
	if m != nil {
		return m.Ssh
	}
	return nil
}

// TestConnectionRequest contains the request of node connection testing.
type TestConnectionRequest struct {
	Node *Node `protobuf:"bytes,1,opt,name=node" json:"node,omitempty"`
}

func (m *TestConnectionRequest) Reset()                    { *m = TestConnectionRequest{} }
func (m *TestConnectionRequest) String() string            { return proto.CompactTextString(m) }
func (*TestConnectionRequest) ProtoMessage()               {}
func (*TestConnectionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *TestConnectionRequest) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

// TestConnectionReply contains the result of node connection testing.
type TestConnectionReply struct {
	Passed  bool   `protobuf:"varint,1,opt,name=passed" json:"passed,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *TestConnectionReply) Reset()                    { *m = TestConnectionReply{} }
func (m *TestConnectionReply) String() string            { return proto.CompactTextString(m) }
func (*TestConnectionReply) ProtoMessage()               {}
func (*TestConnectionReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *TestConnectionReply) GetPassed() bool {
	if m != nil {
		return m.Passed
	}
	return false
}

func (m *TestConnectionReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// CheckNodesRequest contains the request of node pre-checking.
type CheckNodesRequest struct {
	Nodes []*Node `protobuf:"bytes,1,rep,name=nodes" json:"nodes,omitempty"`
}

func (m *CheckNodesRequest) Reset()                    { *m = CheckNodesRequest{} }
func (m *CheckNodesRequest) String() string            { return proto.CompactTextString(m) }
func (*CheckNodesRequest) ProtoMessage()               {}
func (*CheckNodesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CheckNodesRequest) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

// CheckNodesReply contains the result of node pre-checking.
type CheckNodesReply struct {
	Acceptd bool   `protobuf:"varint,1,opt,name=acceptd" json:"acceptd,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *CheckNodesReply) Reset()                    { *m = CheckNodesReply{} }
func (m *CheckNodesReply) String() string            { return proto.CompactTextString(m) }
func (*CheckNodesReply) ProtoMessage()               {}
func (*CheckNodesReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CheckNodesReply) GetAcceptd() bool {
	if m != nil {
		return m.Acceptd
	}
	return false
}

func (m *CheckNodesReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// CheckItem is a check item of node pre-checking
type CheckItem struct {
	Name        string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
}

func (m *CheckItem) Reset()                    { *m = CheckItem{} }
func (m *CheckItem) String() string            { return proto.CompactTextString(m) }
func (*CheckItem) ProtoMessage()               {}
func (*CheckItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *CheckItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CheckItem) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

// ItemCheckResult contains the pre-checking reuslt of an itme
type ItemCheckResult struct {
	Item    *CheckItem `protobuf:"bytes,1,opt,name=item" json:"item,omitempty"`
	Status  string     `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
	Message string     `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
}

func (m *ItemCheckResult) Reset()                    { *m = ItemCheckResult{} }
func (m *ItemCheckResult) String() string            { return proto.CompactTextString(m) }
func (*ItemCheckResult) ProtoMessage()               {}
func (*ItemCheckResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ItemCheckResult) GetItem() *CheckItem {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *ItemCheckResult) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *ItemCheckResult) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// ItemCheckResult contains the pre-checking reuslt of a node
type NodeCheckResult struct {
	NodeName string             `protobuf:"bytes,1,opt,name=nodeName" json:"nodeName,omitempty"`
	Status   string             `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
	Message  string             `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	Items    []*ItemCheckResult `protobuf:"bytes,4,rep,name=items" json:"items,omitempty"`
}

func (m *NodeCheckResult) Reset()                    { *m = NodeCheckResult{} }
func (m *NodeCheckResult) String() string            { return proto.CompactTextString(m) }
func (*NodeCheckResult) ProtoMessage()               {}
func (*NodeCheckResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *NodeCheckResult) GetNodeName() string {
	if m != nil {
		return m.NodeName
	}
	return ""
}

func (m *NodeCheckResult) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *NodeCheckResult) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *NodeCheckResult) GetItems() []*ItemCheckResult {
	if m != nil {
		return m.Items
	}
	return nil
}

// GetCheckNodesResultRequest contains the request of getting nodes check result.
type GetCheckNodesResultRequest struct {
	WithLogs bool `protobuf:"varint,1,opt,name=withLogs" json:"withLogs,omitempty"`
}

func (m *GetCheckNodesResultRequest) Reset()                    { *m = GetCheckNodesResultRequest{} }
func (m *GetCheckNodesResultRequest) String() string            { return proto.CompactTextString(m) }
func (*GetCheckNodesResultRequest) ProtoMessage()               {}
func (*GetCheckNodesResultRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *GetCheckNodesResultRequest) GetWithLogs() bool {
	if m != nil {
		return m.WithLogs
	}
	return false
}

// GetCheckNodesResultReply contains the result of nodes check
type GetCheckNodesResultReply struct {
	Status  string             `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Message string             `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	Nodes   []*NodeCheckResult `protobuf:"bytes,3,rep,name=nodes" json:"nodes,omitempty"`
}

func (m *GetCheckNodesResultReply) Reset()                    { *m = GetCheckNodesResultReply{} }
func (m *GetCheckNodesResultReply) String() string            { return proto.CompactTextString(m) }
func (*GetCheckNodesResultReply) ProtoMessage()               {}
func (*GetCheckNodesResultReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *GetCheckNodesResultReply) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *GetCheckNodesResultReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetCheckNodesResultReply) GetNodes() []*NodeCheckResult {
	if m != nil {
		return m.Nodes
	}
	return nil
}

// ClusterConfig contains the configuraton of a cluster
type ClusterConfig struct {
	ClusterName      string                       `protobuf:"bytes,1,opt,name=clusterName" json:"clusterName,omitempty"`
	NetInterfaceName string                       `protobuf:"bytes,2,opt,name=netInterfaceName" json:"netInterfaceName,omitempty"`
	NodePortRange    *ClusterConfig_NodePortRange `protobuf:"bytes,3,opt,name=nodePortRange" json:"nodePortRange,omitempty"`
	Vip              string                       `protobuf:"bytes,4,opt,name=vip" json:"vip,omitempty"`
	NodeLabels       map[string]string            `protobuf:"bytes,5,rep,name=nodeLabels" json:"nodeLabels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	NodeAnnotations  map[string]string            `protobuf:"bytes,6,rep,name=nodeAnnotations" json:"nodeAnnotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *ClusterConfig) Reset()                    { *m = ClusterConfig{} }
func (m *ClusterConfig) String() string            { return proto.CompactTextString(m) }
func (*ClusterConfig) ProtoMessage()               {}
func (*ClusterConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *ClusterConfig) GetClusterName() string {
	if m != nil {
		return m.ClusterName
	}
	return ""
}

func (m *ClusterConfig) GetNetInterfaceName() string {
	if m != nil {
		return m.NetInterfaceName
	}
	return ""
}

func (m *ClusterConfig) GetNodePortRange() *ClusterConfig_NodePortRange {
	if m != nil {
		return m.NodePortRange
	}
	return nil
}

func (m *ClusterConfig) GetVip() string {
	if m != nil {
		return m.Vip
	}
	return ""
}

func (m *ClusterConfig) GetNodeLabels() map[string]string {
	if m != nil {
		return m.NodeLabels
	}
	return nil
}

func (m *ClusterConfig) GetNodeAnnotations() map[string]string {
	if m != nil {
		return m.NodeAnnotations
	}
	return nil
}

type ClusterConfig_NodePortRange struct {
	From uint32 `protobuf:"varint,1,opt,name=from" json:"from,omitempty"`
	To   uint32 `protobuf:"varint,2,opt,name=to" json:"to,omitempty"`
}

func (m *ClusterConfig_NodePortRange) Reset()                    { *m = ClusterConfig_NodePortRange{} }
func (m *ClusterConfig_NodePortRange) String() string            { return proto.CompactTextString(m) }
func (*ClusterConfig_NodePortRange) ProtoMessage()               {}
func (*ClusterConfig_NodePortRange) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11, 2} }

func (m *ClusterConfig_NodePortRange) GetFrom() uint32 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *ClusterConfig_NodePortRange) GetTo() uint32 {
	if m != nil {
		return m.To
	}
	return 0
}

type Taint struct {
	Key    string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value  string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	Effect string `protobuf:"bytes,3,opt,name=effect" json:"effect,omitempty"`
}

func (m *Taint) Reset()                    { *m = Taint{} }
func (m *Taint) String() string            { return proto.CompactTextString(m) }
func (*Taint) ProtoMessage()               {}
func (*Taint) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *Taint) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Taint) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Taint) GetEffect() string {
	if m != nil {
		return m.Effect
	}
	return ""
}

// NodeDeployConfig contains the deploy configuration for a node
type NodeDeployConfig struct {
	Node   *Node             `protobuf:"bytes,1,opt,name=node" json:"node,omitempty"`
	Roles  []NodeRoleType    `protobuf:"varint,2,rep,packed,name=roles,enum=protos.NodeRoleType" json:"roles,omitempty"`
	Labels map[string]string `protobuf:"bytes,3,rep,name=labels" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Taints []*Taint          `protobuf:"bytes,4,rep,name=taints" json:"taints,omitempty"`
}

func (m *NodeDeployConfig) Reset()                    { *m = NodeDeployConfig{} }
func (m *NodeDeployConfig) String() string            { return proto.CompactTextString(m) }
func (*NodeDeployConfig) ProtoMessage()               {}
func (*NodeDeployConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *NodeDeployConfig) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *NodeDeployConfig) GetRoles() []NodeRoleType {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *NodeDeployConfig) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *NodeDeployConfig) GetTaints() []*Taint {
	if m != nil {
		return m.Taints
	}
	return nil
}

// DeployRequest contains the request of a deploy.
type DeployRequest struct {
	Nodes   []*NodeDeployConfig `protobuf:"bytes,1,rep,name=nodes" json:"nodes,omitempty"`
	Cluster *ClusterConfig      `protobuf:"bytes,2,opt,name=cluster" json:"cluster,omitempty"`
}

func (m *DeployRequest) Reset()                    { *m = DeployRequest{} }
func (m *DeployRequest) String() string            { return proto.CompactTextString(m) }
func (*DeployRequest) ProtoMessage()               {}
func (*DeployRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *DeployRequest) GetNodes() []*NodeDeployConfig {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *DeployRequest) GetCluster() *ClusterConfig {
	if m != nil {
		return m.Cluster
	}
	return nil
}

// DeployReply contains the response of a deploy request.
type DeployReply struct {
	Acceptd bool   `protobuf:"varint,1,opt,name=acceptd" json:"acceptd,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *DeployReply) Reset()                    { *m = DeployReply{} }
func (m *DeployReply) String() string            { return proto.CompactTextString(m) }
func (*DeployReply) ProtoMessage()               {}
func (*DeployReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *DeployReply) GetAcceptd() bool {
	if m != nil {
		return m.Acceptd
	}
	return false
}

func (m *DeployReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// GetDeployResultRequest contains the request of getting deploy result.
type GetDeployResultRequest struct {
	WithLogs bool `protobuf:"varint,1,opt,name=withLogs" json:"withLogs,omitempty"`
}

func (m *GetDeployResultRequest) Reset()                    { *m = GetDeployResultRequest{} }
func (m *GetDeployResultRequest) String() string            { return proto.CompactTextString(m) }
func (*GetDeployResultRequest) ProtoMessage()               {}
func (*GetDeployResultRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *GetDeployResultRequest) GetWithLogs() bool {
	if m != nil {
		return m.WithLogs
	}
	return false
}

// DeployComponent represents a component in a deploy
type DeployComponent struct {
	Name                string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Description         string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	FailureCanBeIgnored bool   `protobuf:"varint,3,opt,name=failureCanBeIgnored" json:"failureCanBeIgnored,omitempty"`
}

func (m *DeployComponent) Reset()                    { *m = DeployComponent{} }
func (m *DeployComponent) String() string            { return proto.CompactTextString(m) }
func (*DeployComponent) ProtoMessage()               {}
func (*DeployComponent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *DeployComponent) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DeployComponent) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *DeployComponent) GetFailureCanBeIgnored() bool {
	if m != nil {
		return m.FailureCanBeIgnored
	}
	return false
}

// DeployItem represents a deploy action of a component in a node for a role.
type DeployItem struct {
	Role      string           `protobuf:"bytes,1,opt,name=role" json:"role,omitempty"`
	NodeName  string           `protobuf:"bytes,2,opt,name=nodeName" json:"nodeName,omitempty"`
	Component *DeployComponent `protobuf:"bytes,3,opt,name=component" json:"component,omitempty"`
}

func (m *DeployItem) Reset()                    { *m = DeployItem{} }
func (m *DeployItem) String() string            { return proto.CompactTextString(m) }
func (*DeployItem) ProtoMessage()               {}
func (*DeployItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *DeployItem) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *DeployItem) GetNodeName() string {
	if m != nil {
		return m.NodeName
	}
	return ""
}

func (m *DeployItem) GetComponent() *DeployComponent {
	if m != nil {
		return m.Component
	}
	return nil
}

// DeployItemResult represents the deploy result of a component in a node for a role.
type DeployItemResult struct {
	DeployItem *DeployItem `protobuf:"bytes,1,opt,name=deployItem" json:"deployItem,omitempty"`
	Status     string      `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
	Message    string      `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	Logs       string      `protobuf:"bytes,4,opt,name=logs" json:"logs,omitempty"`
}

func (m *DeployItemResult) Reset()                    { *m = DeployItemResult{} }
func (m *DeployItemResult) String() string            { return proto.CompactTextString(m) }
func (*DeployItemResult) ProtoMessage()               {}
func (*DeployItemResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *DeployItemResult) GetDeployItem() *DeployItem {
	if m != nil {
		return m.DeployItem
	}
	return nil
}

func (m *DeployItemResult) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *DeployItemResult) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *DeployItemResult) GetLogs() string {
	if m != nil {
		return m.Logs
	}
	return ""
}

// GetDeployResultReply represents the result of a deploy
type GetDeployResultReply struct {
	Status  string              `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Message string              `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	Items   []*DeployItemResult `protobuf:"bytes,3,rep,name=items" json:"items,omitempty"`
}

func (m *GetDeployResultReply) Reset()                    { *m = GetDeployResultReply{} }
func (m *GetDeployResultReply) String() string            { return proto.CompactTextString(m) }
func (*GetDeployResultReply) ProtoMessage()               {}
func (*GetDeployResultReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *GetDeployResultReply) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *GetDeployResultReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetDeployResultReply) GetItems() []*DeployItemResult {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*SSH)(nil), "protos.SSH")
	proto.RegisterType((*SSH_Auth)(nil), "protos.SSH.Auth")
	proto.RegisterType((*Node)(nil), "protos.Node")
	proto.RegisterType((*TestConnectionRequest)(nil), "protos.TestConnectionRequest")
	proto.RegisterType((*TestConnectionReply)(nil), "protos.TestConnectionReply")
	proto.RegisterType((*CheckNodesRequest)(nil), "protos.CheckNodesRequest")
	proto.RegisterType((*CheckNodesReply)(nil), "protos.CheckNodesReply")
	proto.RegisterType((*CheckItem)(nil), "protos.CheckItem")
	proto.RegisterType((*ItemCheckResult)(nil), "protos.ItemCheckResult")
	proto.RegisterType((*NodeCheckResult)(nil), "protos.NodeCheckResult")
	proto.RegisterType((*GetCheckNodesResultRequest)(nil), "protos.GetCheckNodesResultRequest")
	proto.RegisterType((*GetCheckNodesResultReply)(nil), "protos.GetCheckNodesResultReply")
	proto.RegisterType((*ClusterConfig)(nil), "protos.ClusterConfig")
	proto.RegisterType((*ClusterConfig_NodePortRange)(nil), "protos.ClusterConfig.NodePortRange")
	proto.RegisterType((*Taint)(nil), "protos.Taint")
	proto.RegisterType((*NodeDeployConfig)(nil), "protos.NodeDeployConfig")
	proto.RegisterType((*DeployRequest)(nil), "protos.DeployRequest")
	proto.RegisterType((*DeployReply)(nil), "protos.DeployReply")
	proto.RegisterType((*GetDeployResultRequest)(nil), "protos.GetDeployResultRequest")
	proto.RegisterType((*DeployComponent)(nil), "protos.DeployComponent")
	proto.RegisterType((*DeployItem)(nil), "protos.DeployItem")
	proto.RegisterType((*DeployItemResult)(nil), "protos.DeployItemResult")
	proto.RegisterType((*GetDeployResultReply)(nil), "protos.GetDeployResultReply")
	proto.RegisterEnum("protos.NodeRoleType", NodeRoleType_name, NodeRoleType_value)
	proto.RegisterEnum("protos.SSH_AuthType", SSH_AuthType_name, SSH_AuthType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for DeployContoller service

type DeployContollerClient interface {
	TestConnection(ctx context.Context, in *TestConnectionRequest, opts ...grpc.CallOption) (*TestConnectionReply, error)
	CheckNodes(ctx context.Context, in *CheckNodesRequest, opts ...grpc.CallOption) (*CheckNodesReply, error)
	GetCheckNodesResult(ctx context.Context, in *GetCheckNodesResultRequest, opts ...grpc.CallOption) (*GetCheckNodesResultReply, error)
	Deploy(ctx context.Context, in *DeployRequest, opts ...grpc.CallOption) (*DeployReply, error)
	GetDeployResult(ctx context.Context, in *GetDeployResultRequest, opts ...grpc.CallOption) (*GetDeployResultReply, error)
}

type deployContollerClient struct {
	cc *grpc.ClientConn
}

func NewDeployContollerClient(cc *grpc.ClientConn) DeployContollerClient {
	return &deployContollerClient{cc}
}

func (c *deployContollerClient) TestConnection(ctx context.Context, in *TestConnectionRequest, opts ...grpc.CallOption) (*TestConnectionReply, error) {
	out := new(TestConnectionReply)
	err := grpc.Invoke(ctx, "/protos.DeployContoller/TestConnection", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deployContollerClient) CheckNodes(ctx context.Context, in *CheckNodesRequest, opts ...grpc.CallOption) (*CheckNodesReply, error) {
	out := new(CheckNodesReply)
	err := grpc.Invoke(ctx, "/protos.DeployContoller/CheckNodes", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deployContollerClient) GetCheckNodesResult(ctx context.Context, in *GetCheckNodesResultRequest, opts ...grpc.CallOption) (*GetCheckNodesResultReply, error) {
	out := new(GetCheckNodesResultReply)
	err := grpc.Invoke(ctx, "/protos.DeployContoller/GetCheckNodesResult", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deployContollerClient) Deploy(ctx context.Context, in *DeployRequest, opts ...grpc.CallOption) (*DeployReply, error) {
	out := new(DeployReply)
	err := grpc.Invoke(ctx, "/protos.DeployContoller/Deploy", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deployContollerClient) GetDeployResult(ctx context.Context, in *GetDeployResultRequest, opts ...grpc.CallOption) (*GetDeployResultReply, error) {
	out := new(GetDeployResultReply)
	err := grpc.Invoke(ctx, "/protos.DeployContoller/GetDeployResult", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DeployContoller service

type DeployContollerServer interface {
	TestConnection(context.Context, *TestConnectionRequest) (*TestConnectionReply, error)
	CheckNodes(context.Context, *CheckNodesRequest) (*CheckNodesReply, error)
	GetCheckNodesResult(context.Context, *GetCheckNodesResultRequest) (*GetCheckNodesResultReply, error)
	Deploy(context.Context, *DeployRequest) (*DeployReply, error)
	GetDeployResult(context.Context, *GetDeployResultRequest) (*GetDeployResultReply, error)
}

func RegisterDeployContollerServer(s *grpc.Server, srv DeployContollerServer) {
	s.RegisterService(&_DeployContoller_serviceDesc, srv)
}

func _DeployContoller_TestConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployContollerServer).TestConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.DeployContoller/TestConnection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployContollerServer).TestConnection(ctx, req.(*TestConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeployContoller_CheckNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployContollerServer).CheckNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.DeployContoller/CheckNodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployContollerServer).CheckNodes(ctx, req.(*CheckNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeployContoller_GetCheckNodesResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCheckNodesResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployContollerServer).GetCheckNodesResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.DeployContoller/GetCheckNodesResult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployContollerServer).GetCheckNodesResult(ctx, req.(*GetCheckNodesResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeployContoller_Deploy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployContollerServer).Deploy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.DeployContoller/Deploy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployContollerServer).Deploy(ctx, req.(*DeployRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeployContoller_GetDeployResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeployResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployContollerServer).GetDeployResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.DeployContoller/GetDeployResult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployContollerServer).GetDeployResult(ctx, req.(*GetDeployResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DeployContoller_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.DeployContoller",
	HandlerType: (*DeployContollerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TestConnection",
			Handler:    _DeployContoller_TestConnection_Handler,
		},
		{
			MethodName: "CheckNodes",
			Handler:    _DeployContoller_CheckNodes_Handler,
		},
		{
			MethodName: "GetCheckNodesResult",
			Handler:    _DeployContoller_GetCheckNodesResult_Handler,
		},
		{
			MethodName: "Deploy",
			Handler:    _DeployContoller_Deploy_Handler,
		},
		{
			MethodName: "GetDeployResult",
			Handler:    _DeployContoller_GetDeployResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "deploy_controller.proto",
}

func init() { proto.RegisterFile("deploy_controller.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1101 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x57, 0xdd, 0x6e, 0x1a, 0x47,
	0x14, 0xce, 0xc2, 0x42, 0xf0, 0x21, 0x18, 0x32, 0xb6, 0xe3, 0xed, 0xb6, 0x89, 0xd0, 0x36, 0x96,
	0x2c, 0x4b, 0xa5, 0x11, 0xe9, 0x4f, 0x52, 0xb5, 0x17, 0x98, 0x20, 0x07, 0x25, 0x75, 0xdc, 0x01,
	0x35, 0xea, 0x45, 0x55, 0x6d, 0x96, 0xc1, 0xde, 0x66, 0xd9, 0xd9, 0xee, 0x0c, 0x69, 0x51, 0x6f,
	0xfa, 0x00, 0x55, 0xf3, 0x40, 0x7d, 0xb9, 0x6a, 0xfe, 0xf0, 0x2c, 0x86, 0x34, 0xf1, 0x15, 0x33,
	0x73, 0xce, 0xf9, 0xbe, 0xf3, 0x37, 0x73, 0x16, 0xd8, 0x9f, 0x90, 0x2c, 0xa1, 0x8b, 0x5f, 0x22,
	0x9a, 0xf2, 0x9c, 0x26, 0x09, 0xc9, 0x3b, 0x59, 0x4e, 0x39, 0x45, 0x55, 0xf9, 0xc3, 0x82, 0x7f,
	0x1d, 0x28, 0x8f, 0x46, 0x4f, 0x11, 0x02, 0x37, 0xa3, 0x39, 0xf7, 0x9c, 0xb6, 0x73, 0xd8, 0xc0,
	0x72, 0x8d, 0xee, 0x83, 0x1b, 0xce, 0xf9, 0x85, 0x57, 0x6a, 0x3b, 0x87, 0xf5, 0x6e, 0x4b, 0x59,
	0xb2, 0xce, 0x68, 0xf4, 0xb4, 0xd3, 0x9b, 0xf3, 0x0b, 0x2c, 0xa5, 0xfe, 0x19, 0xb8, 0x62, 0x87,
	0x0e, 0xc1, 0xe5, 0x8b, 0x8c, 0x48, 0x84, 0xed, 0xee, 0xee, 0xaa, 0xf6, 0x78, 0x91, 0x11, 0x2c,
	0x35, 0xd0, 0x3d, 0x80, 0x28, 0x27, 0x13, 0x92, 0xf2, 0x38, 0x4c, 0x24, 0xfa, 0x16, 0xb6, 0x4e,
	0x82, 0x43, 0xa8, 0x19, 0x0b, 0x74, 0x0b, 0x6a, 0x67, 0xbd, 0xd1, 0xe8, 0xe5, 0x0b, 0xfc, 0xa4,
	0x75, 0x03, 0x6d, 0x03, 0x9c, 0xe1, 0xe1, 0x8f, 0xbd, 0xf1, 0xe0, 0xd9, 0xe0, 0xa7, 0x96, 0x13,
	0x0c, 0xc1, 0x3d, 0xa5, 0x13, 0x22, 0xbc, 0x4f, 0xc3, 0x99, 0xe2, 0xde, 0xc2, 0x72, 0x8d, 0xb6,
	0xa1, 0x14, 0x67, 0x1a, 0xbd, 0x14, 0x67, 0xe8, 0x2e, 0x94, 0x19, 0xbb, 0xf0, 0xca, 0x32, 0x98,
	0xba, 0xe5, 0x1e, 0x16, 0xe7, 0xc1, 0x63, 0xd8, 0x1b, 0x13, 0xc6, 0xfb, 0x34, 0x4d, 0x49, 0xc4,
	0x63, 0x9a, 0x62, 0xf2, 0xdb, 0x9c, 0x30, 0x8e, 0xda, 0xe0, 0xa6, 0x74, 0xa2, 0xb0, 0xeb, 0xdd,
	0x5b, 0xc6, 0x50, 0xf0, 0x62, 0x29, 0x09, 0x4e, 0x60, 0x67, 0xd5, 0x34, 0x4b, 0x16, 0xe8, 0x0e,
	0x54, 0xb3, 0x90, 0x31, 0x32, 0x91, 0xa6, 0x35, 0xac, 0x77, 0xc8, 0x83, 0x9b, 0x33, 0xc2, 0x58,
	0x78, 0x4e, 0xb4, 0x77, 0x66, 0x1b, 0x7c, 0x0d, 0xb7, 0xfb, 0x17, 0x24, 0x7a, 0x2d, 0xb0, 0x99,
	0xe1, 0x0f, 0xa0, 0x22, 0x58, 0x98, 0xe7, 0xb4, 0xcb, 0x57, 0x1c, 0x50, 0xa2, 0x60, 0x00, 0x4d,
	0xdb, 0x50, 0xb0, 0x7b, 0x70, 0x33, 0x8c, 0x22, 0x92, 0x71, 0x43, 0x6f, 0xb6, 0xef, 0xe0, 0xef,
	0xc1, 0x96, 0x84, 0x19, 0x72, 0x32, 0x5b, 0x9b, 0xd3, 0x36, 0xd4, 0x27, 0x84, 0x45, 0x79, 0x9c,
	0x89, 0x30, 0xb5, 0xb9, 0x7d, 0x14, 0xfc, 0x0a, 0x4d, 0x61, 0x2d, 0x61, 0x30, 0x61, 0xf3, 0x84,
	0xa3, 0x03, 0x70, 0x63, 0x4e, 0x66, 0x3a, 0x81, 0xb7, 0x8d, 0xff, 0x4b, 0x26, 0x2c, 0xc5, 0x22,
	0x5d, 0x8c, 0x87, 0x7c, 0xce, 0x34, 0xac, 0xde, 0xd9, 0xee, 0x96, 0x8b, 0xee, 0xfe, 0xe3, 0x40,
	0x53, 0x44, 0x6c, 0x93, 0xf9, 0x50, 0x13, 0x29, 0x39, 0xbd, 0xf4, 0x7c, 0xb9, 0xff, 0x70, 0x06,
	0xf4, 0x19, 0x54, 0x84, 0x6f, 0xcc, 0x73, 0x65, 0xee, 0xf7, 0x8d, 0xef, 0x2b, 0x21, 0x62, 0xa5,
	0x15, 0x3c, 0x02, 0xff, 0x84, 0x70, 0xbb, 0x12, 0x52, 0xaa, 0x0b, 0xe9, 0x43, 0xed, 0xf7, 0x98,
	0x5f, 0x3c, 0xa7, 0xe7, 0x4c, 0x97, 0x64, 0xb9, 0x0f, 0xfe, 0x04, 0x6f, 0xad, 0xa5, 0xee, 0x23,
	0xed, 0xb6, 0xb3, 0xc9, 0xed, 0xd2, 0x15, 0xb7, 0x55, 0xcb, 0x94, 0x8b, 0x6e, 0xaf, 0x24, 0xcb,
	0x74, 0xcf, 0x5b, 0x17, 0x1a, 0xfd, 0x64, 0xce, 0x38, 0xc9, 0xfb, 0x34, 0x9d, 0xc6, 0xe7, 0xa2,
	0xce, 0x91, 0x3a, 0xb0, 0x12, 0x69, 0x1f, 0xa1, 0x23, 0x68, 0xa5, 0x84, 0x0f, 0x53, 0x4e, 0xf2,
	0x69, 0x18, 0xa9, 0x7c, 0x2b, 0x2f, 0xae, 0x9c, 0xa3, 0x21, 0x34, 0x04, 0xd1, 0x19, 0xcd, 0x39,
	0x0e, 0x53, 0x9d, 0xe5, 0x7a, 0xf7, 0xd3, 0x65, 0x27, 0xd8, 0xdc, 0xd2, 0xc9, 0xa5, 0x2a, 0x2e,
	0x5a, 0xa2, 0x16, 0x94, 0xdf, 0xc4, 0x99, 0xe7, 0x4a, 0x26, 0xb1, 0x44, 0x03, 0x00, 0xa1, 0xf2,
	0x3c, 0x7c, 0x45, 0x12, 0xe6, 0x55, 0x64, 0xc0, 0x07, 0x9b, 0x91, 0x95, 0xde, 0x20, 0xe5, 0xf9,
	0x02, 0x5b, 0x86, 0x68, 0x0c, 0x4d, 0xb1, 0xeb, 0xa5, 0x29, 0xe5, 0xa1, 0xe8, 0x64, 0xe6, 0x55,
	0x25, 0xd6, 0xd1, 0x66, 0x2c, 0x4b, 0x59, 0x01, 0xae, 0x42, 0xf8, 0xdf, 0xa9, 0x06, 0xb5, 0x48,
	0x45, 0x04, 0xaf, 0xc9, 0x42, 0xa7, 0x54, 0x2c, 0xd1, 0x2e, 0x54, 0xde, 0x84, 0xc9, 0xdc, 0xe4,
	0x4f, 0x6d, 0xbe, 0x29, 0x3d, 0x72, 0xfc, 0x63, 0xd8, 0x5d, 0xc7, 0xf3, 0x41, 0x18, 0x0f, 0xa1,
	0x51, 0xc8, 0xa8, 0xb8, 0xd7, 0xd3, 0x9c, 0xce, 0xcc, 0x4b, 0x2f, 0xd6, 0xe2, 0xad, 0xe4, 0x54,
	0xda, 0x36, 0x70, 0x89, 0xd3, 0xe0, 0x04, 0x2a, 0xe3, 0x30, 0x4e, 0xf9, 0xfb, 0x32, 0x89, 0x1e,
	0x25, 0xd3, 0x29, 0x89, 0xb8, 0xbe, 0x41, 0x7a, 0x17, 0xfc, 0x55, 0x82, 0x96, 0xa0, 0x7f, 0x22,
	0xc7, 0xd0, 0xb2, 0xbb, 0xfe, 0xe7, 0x45, 0x45, 0x47, 0x50, 0xc9, 0x69, 0x42, 0xc4, 0x45, 0x2d,
	0xdb, 0xc3, 0x44, 0xaa, 0xd0, 0x84, 0xc8, 0x61, 0xa2, 0x54, 0xd0, 0xb7, 0x50, 0x4d, 0x54, 0xf1,
	0x55, 0xb7, 0xdf, 0xb7, 0x95, 0x6d, 0xde, 0x8e, 0x5d, 0x7b, 0x6d, 0x83, 0x0e, 0xa0, 0xca, 0x45,
	0xa4, 0xe6, 0x8a, 0x37, 0x8c, 0xb5, 0x8c, 0x1f, 0x6b, 0xa1, 0xff, 0x18, 0xea, 0xd7, 0x2c, 0x62,
	0x90, 0x41, 0x43, 0x79, 0x61, 0xde, 0x81, 0x4e, 0xf1, 0x41, 0xf7, 0x36, 0xf9, 0xab, 0xaf, 0x27,
	0xfa, 0x1c, 0x6e, 0xea, 0x9b, 0xa7, 0x27, 0xf1, 0xde, 0xda, 0x96, 0xc4, 0x46, 0x2b, 0xe8, 0x41,
	0xdd, 0x30, 0x5e, 0x77, 0x12, 0x7c, 0x01, 0x77, 0x4e, 0x08, 0x37, 0x28, 0xef, 0xfb, 0x8a, 0x2d,
	0xa0, 0x69, 0x02, 0x98, 0x65, 0x34, 0x25, 0x29, 0xbf, 0xde, 0x14, 0x41, 0x0f, 0x60, 0x67, 0x1a,
	0xc6, 0xc9, 0x3c, 0x27, 0xfd, 0x30, 0x3d, 0x26, 0xc3, 0xf3, 0x94, 0xe6, 0x64, 0x22, 0x7b, 0xab,
	0x86, 0xd7, 0x89, 0x02, 0x06, 0xa0, 0xa8, 0xcd, 0xec, 0x12, 0xcd, 0x61, 0x58, 0xc5, 0xba, 0x30,
	0x19, 0x4a, 0x2b, 0x93, 0xe1, 0x4b, 0xd8, 0x8a, 0x8c, 0xcb, 0xfa, 0x75, 0x5a, 0x3e, 0x9a, 0x2b,
	0x11, 0xe1, 0x4b, 0xcd, 0xe0, 0x6f, 0x07, 0x5a, 0x97, 0xac, 0x7a, 0x02, 0x75, 0x01, 0x26, 0xcb,
	0x33, 0xdd, 0xe3, 0xa8, 0x08, 0x26, 0xb5, 0x2d, 0xad, 0x6b, 0x4c, 0x26, 0x04, 0x6e, 0x22, 0x4a,
	0xa0, 0x5e, 0x42, 0xb9, 0x0e, 0xfe, 0x80, 0xdd, 0x2b, 0x45, 0xbb, 0xde, 0x00, 0xe9, 0x98, 0xb9,
	0x57, 0x2e, 0xb6, 0xe8, 0x6a, 0xb0, 0x7a, 0xf0, 0x1d, 0x3d, 0x80, 0x5b, 0xf6, 0xd5, 0x44, 0x35,
	0x70, 0x07, 0xe3, 0xbe, 0xf8, 0x62, 0x03, 0xa8, 0x7e, 0xdf, 0x1b, 0x8d, 0x07, 0xb8, 0xe5, 0x88,
	0xf5, 0xcb, 0x17, 0xf8, 0xd9, 0x00, 0xb7, 0x4a, 0xdd, 0xb7, 0xe5, 0xcb, 0x5e, 0x49, 0xb9, 0xfc,
	0x32, 0x45, 0xa7, 0xb0, 0x5d, 0xfc, 0x8e, 0x42, 0x77, 0x97, 0xb7, 0x71, 0xdd, 0xa7, 0x99, 0xff,
	0xf1, 0x26, 0x71, 0x96, 0x2c, 0x82, 0x1b, 0xe8, 0x18, 0xe0, 0x72, 0xa2, 0xa2, 0x8f, 0x0a, 0x1f,
	0x1e, 0xf6, 0x27, 0x96, 0xbf, 0xbf, 0x4e, 0xa4, 0x30, 0x7e, 0x86, 0x9d, 0x35, 0x83, 0x19, 0x05,
	0xc6, 0x62, 0xf3, 0xbc, 0xf7, 0xdb, 0xef, 0xd4, 0x51, 0xf0, 0x5f, 0x41, 0x55, 0x65, 0x01, 0xed,
	0x15, 0x73, 0x6c, 0x40, 0x76, 0x56, 0x8f, 0x95, 0xdd, 0x0f, 0xd0, 0x5c, 0x29, 0x35, 0xba, 0x67,
	0xd1, 0xad, 0xb9, 0xb8, 0xfe, 0x27, 0x1b, 0xe5, 0x12, 0xf2, 0x95, 0xfa, 0x47, 0xf0, 0xf0, 0xbf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xfe, 0xe0, 0x61, 0x97, 0x33, 0x0c, 0x00, 0x00,
}
